# Generated by Django 2.2.19 on 2021-04-04 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='money',
            field=models.TextField(default='1000000'),
        ),
        migrations.AddField(
            model_name='post',
            name='name',
            field=models.TextField(default='Gina'),
        ),
        migrations.AddField(
            model_name='post',
            name='year',
            field=models.TextField(default='1'),
        ),
    ]
